[package]
org = "ballerina"
name = "os"
version = "1.6.0"
authors = ["Ballerina"]
keywords = ["environment"]
repository = "https://github.com/ballerina-platform/module-ballerina-os"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "os-native"
version = "1.6.0"
path = "../native/build/libs/os-native-1.6.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
version = "1.4.0"
path = "./lib/io-native-1.4.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "os-test-utils"
version = "1.6.0"
path = "../test-utils/build/libs/os-test-utils-1.6.0.jar"
